<?php

namespace Cesurapp\ApiBundle\Thor\Command;

use Cesurapp\ApiBundle\Thor\Extractor\ThorExtractor;
use Cesurapp\ApiBundle\Thor\Generator\TypeScriptGenerator;
use Symfony\Component\Console\Attribute\AsCommand;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputArgument;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Input\InputOption;
use Symfony\Component\Console\Output\OutputInterface;
use Symfony\Component\DependencyInjection\Attribute\Autowire;

/**
 * Thor Generate Api Documentation to JSON File.
 */
#[AsCommand(name: 'thor:extract', description: 'Thor Extract Api Documentation to TS File')]
class ThorGenerateCommand extends Command
{
    public function __construct(
        private readonly ThorExtractor $extractor,
        #[Autowire('%kernel.project_dir%')] private readonly string $projectDir,
    ) {
        parent::__construct();
    }

    protected function configure(): void
    {
        $this
            ->addArgument('path', InputArgument::REQUIRED, 'Files extract path. The directory is replaced.')
            ->addOption('force', 'f', InputOption::VALUE_NONE, 'Replace the directory even if it was not generated by thor:extract.');
    }

    protected function execute(InputInterface $input, OutputInterface $output): int
    {
        $path = $input->getArgument('path');

        // The target is deleted and rewritten: never the project itself or a directory above it
        if (self::containsProject($path, $this->projectDir)) {
            $output->writeln(sprintf('<error>"%s" contains the project, refusing to replace it.</error>', $path));

            return Command::FAILURE;
        }

        if (file_exists($path) && !$input->getOption('force') && is_dir($path) && !TypeScriptGenerator::isGeneratedDirectory($path)) {
            $output->writeln(sprintf('<error>"%s" is not empty and was not generated by thor:extract, refusing to delete it. Pick another path or pass --force.</error>', $path));

            return Command::FAILURE;
        }

        // Generate
        $apiData = $this->extractor->extractData(true);
        $tsGenerator = new TypeScriptGenerator($apiData);

        // Copy Custom Directory
        $tsGenerator->generate()->copyFiles($path, (bool) $input->getOption('force'));

        return Command::SUCCESS;
    }

    /**
     * Whether $path is $projectDir or one of its parents.
     */
    public static function containsProject(string $path, string $projectDir): bool
    {
        $target = realpath($path);
        $project = realpath($projectDir);
        if (false === $target || false === $project) {
            return false;
        }

        return str_starts_with($project.\DIRECTORY_SEPARATOR, rtrim($target, \DIRECTORY_SEPARATOR).\DIRECTORY_SEPARATOR);
    }
}
