<?php

namespace Cesurapp\ApiBundle\Thor\Generator;

use Cesurapp\ApiBundle\Thor\Extractor\ThorExtractor;
use Symfony\Component\Filesystem\Filesystem;
use Symfony\Component\HttpFoundation\File\File;

class TypeScriptGenerator
{
    /** Written into every generated client; copyFiles() only replaces a directory that carries it. */
    public const string MARKER = '.thor';

    private string $path;
    private TypeScriptHelper $helper;
    private array $routeGroups = [];

    public function __construct(private readonly array $data)
    {
        $this->routeGroups = array_map(
            static fn ($arr) => array_column($arr, 'routeGroup'),
            array_filter($this->data, static fn ($k) => !str_starts_with($k, '_'), ARRAY_FILTER_USE_KEY)
        );
        $this->routeGroups = array_unique(array_merge(...array_values($this->routeGroups)));

        // Create Template Helper
        $this->helper = new TypeScriptHelper();

        // Generate Path (removed again in __destruct)
        $this->path = rtrim(sys_get_temp_dir(), '/\\').\DIRECTORY_SEPARATOR.'thor_'.bin2hex(random_bytes(8));
        foreach ($this->routeGroups as $route) {
            foreach (['response', 'request', 'query', 'table', 'resource'] as $dir) {
                $p = sprintf('%s/%s/%s', $this->path, $route, $dir);
                if (!mkdir($p, 0777, true) && !is_dir($p)) {
                    throw new \RuntimeException(sprintf('Directory "%s" was not created', $p));
                }
            }
        }

        foreach (['enum'] as $dir) {
            $p = sprintf('%s/%s', $this->path, $dir);
            if (!mkdir($p, 0777, true) && !is_dir($p)) {
                throw new \RuntimeException(sprintf('Directory "%s" was not created', $p));
            }
        }
    }

    public function __destruct()
    {
        if (is_dir($this->path)) {
            new Filesystem()->remove($this->path);
        }
    }

    public function getPath(): string
    {
        return $this->path;
    }

    /**
     * Generate TS Files.
     */
    public function generate(): self
    {
        foreach ($this->data as $key => $groupRoutes) {
            if (str_starts_with($key, '_')) {
                switch ($key) {
                    case '_enums': $this->generateEnum($groupRoutes);
                        break;
                    case '_resource': $this->generateResources($groupRoutes);
                }

                continue;
            }

            foreach ($groupRoutes as $route) {
                $this->generateResponse($route);
                $this->generateRequest($route);
                $this->generateQuery($route);
                $this->generateTable($route);
            }
        }

        // Render Route Groups
        foreach ($this->routeGroups as $routeGroup) {
            file_put_contents($this->path."/$routeGroup.ts", $this->renderTemplate('routeGroup.ts.php', [
                'data' => array_map(function ($data) use ($routeGroup) {
                    return array_filter($data, fn ($item) => $item['routeGroup'] === $routeGroup);
                }, array_filter($this->data, static fn ($k) => !str_starts_with($k, '_'), ARRAY_FILTER_USE_KEY)),
                'routeGroup' => $routeGroup,
            ]));
        }
        // Render Index
        file_put_contents($this->path.'/index.ts', $this->renderTemplate('index.ts.php', [
            'routeGroups' => $this->routeGroups,
        ]));

        // Render Dependency
        file_put_contents($this->path.'/flatten.ts', $this->renderTemplate('flatten.ts.php', [
            'data' => $this->data,
        ]));
        file_put_contents($this->path.'/package.json', $this->renderTemplate('package.json.php', []));
        file_put_contents($this->path.'/tsconfig.json', $this->renderTemplate('tsconfig.json.php', []));
        file_put_contents($this->path.'/'.self::MARKER, "Generated by cesurapp/api-bundle (thor:extract). This directory is replaced on every run.\n");

        return $this;
    }

    /**
     * Compress TS Library to a .tar.gz archive, in PHP (no shell, no tar binary).
     *
     * Built under a unique name and renamed into place, so concurrent calls never read a half
     * written or another request's archive.
     */
    public function compress(?string $path = null, string $fileName = 'Api.tar.gz'): File
    {
        $dir = rtrim($path ?? sys_get_temp_dir(), '/\\');
        if (!is_dir($dir) && !mkdir($dir, 0777, true) && !is_dir($dir)) {
            throw new \RuntimeException(sprintf('Directory "%s" was not created', $dir));
        }

        if (!\Phar::canCompress(\Phar::GZ)) {
            throw new \RuntimeException('The zlib extension is required to compress the TypeScript client.');
        }

        // PharData derives the archive type from the first dot of the name: keep it dot-free
        $tar = $dir.\DIRECTORY_SEPARATOR.'thor_'.bin2hex(random_bytes(8)).'.tar';
        try {
            $archive = new \PharData($tar);
            $archive->buildFromDirectory($this->path);
            $archive->compress(\Phar::GZ);
            unset($archive);

            if (!rename($tar.'.gz', $dir.\DIRECTORY_SEPARATOR.$fileName)) {
                throw new \RuntimeException(sprintf('Archive "%s" could not be written.', $fileName));
            }
        } finally {
            foreach ([$tar, $tar.'.gz'] as $leftover) {
                if (file_exists($leftover)) {
                    @unlink($leftover);
                }
            }
        }

        return new File($dir.\DIRECTORY_SEPARATOR.$fileName);
    }

    /**
     * Copy Generated Directory to Custom Path.
     *
     * The target is deleted first, so it must be a directory this generator wrote (marker file,
     * or the index.ts + flatten.ts pair of older clients) or be empty — unless $force.
     */
    public function copyFiles(string $path, bool $force = false): void
    {
        $fs = new Filesystem();

        // Remove Old Path
        if (file_exists($path)) {
            if (!is_dir($path)) {
                throw new \RuntimeException(sprintf('"%s" is not a directory.', $path));
            }

            if (!$force && !self::isGeneratedDirectory($path)) {
                throw new \RuntimeException(sprintf('"%s" is not empty and was not generated by thor:extract, refusing to delete it. Pick another path or pass --force.', $path));
            }

            $fs->remove($path);
        }

        $fs->mirror($this->path, $path);
    }

    public static function isGeneratedDirectory(string $path): bool
    {
        $entries = array_diff(scandir($path) ?: [], ['.', '..']);

        return !$entries
            || is_file($path.'/'.self::MARKER)
            || (is_file($path.'/index.ts') && is_file($path.'/flatten.ts'));
    }

    /**
     * Render PHP Template.
     */
    private function renderTemplate(string $template, array $data = []): string
    {
        $data['helper'] = $this->helper;
        extract($data, EXTR_OVERWRITE);

        ob_start();
        include __DIR__.'/../Template/typescript/'.$template;

        $output = ob_get_clean();
        if (false === $output) {
            throw new \LogicException('The template closed the output buffer.');
        }

        return $output;
    }

    /**
     * Generate Response Parameters.
     */
    private function generateResponse(array $route): void
    {
        if (!$route['response']) {
            return;
        }

        $resources = [];
        array_walk_recursive($route, static function ($val) use (&$resources) {
            if (is_string($val) && ThorExtractor::isResourceClass($val)) {
                $resources[] = sprintf('%s/resource/%s', ThorExtractor::basePath($val), ThorExtractor::baseClass($val));
            }
        });

        $name = sprintf('%sResponse.ts', ucfirst($route['shortName']));
        file_put_contents(sprintf('%s/%s/response/%s', $this->path, $route['routeGroup'], $name), $this->renderTemplate('response.ts.php', [
            'data' => $route,
            'resources' => $resources,
        ]));
    }

    /**
     * Generate POST|PUT|PATCH Parameters.
     */
    private function generateRequest(array $route): void
    {
        if (!$route['request']) {
            return;
        }

        $name = sprintf('%sRequest.ts', ucfirst($route['shortName']));
        file_put_contents(sprintf('%s/%s/request/%s', $this->path, $route['routeGroup'], $name), $this->renderTemplate('request.ts.php', [
            'data' => $route,
        ]));
    }

    /**
     * Generate GET Parameters.
     */
    private function generateQuery(array $route): void
    {
        if (!$route['query']) {
            return;
        }

        $name = sprintf('%sQuery.ts', ucfirst($route['shortName']));
        file_put_contents(sprintf('%s/%s/query/%s', $this->path, $route['routeGroup'], $name), $this->renderTemplate('query.ts.php', [
            'data' => $route,
        ]));
    }

    /**
     * Generate DataTable Columns.
     */
    private function generateTable(array $route): void
    {
        if (!$route['table']) {
            return;
        }

        $name = sprintf('%sTable.ts', ucfirst($route['shortName']));
        file_put_contents(sprintf('%s/%s/table/%s', $this->path, $route['routeGroup'], $name), $this->renderTemplate('table.ts.php', [
            'data' => $route,
        ]));
    }

    /**
     * Generate Enums. A `_enums` entry is either an enum class (rendered as a TS enum) or an
     * array (rendered as a const data table of arbitrary depth — enum-attached tables such as
     * per-tier limits that would otherwise have to travel as JSON on every request).
     */
    private function generateEnum(array $enumsGroup): void
    {
        foreach ($enumsGroup as $namespace => $enumData) {
            $file = 'Permission' === $namespace ? 'permission.ts.php' : (is_array($enumData) ? 'enum-const.ts.php' : 'enum.ts.php');
            $name = sprintf('%s.ts', ucfirst($namespace));
            $enumData = is_array($enumData) ? $enumData : $enumData::cases();
            file_put_contents(sprintf('%s/enum/%s', $this->path, $name), $this->renderTemplate($file, [
                'namespace' => $namespace,
                'data' => $enumData,
            ]));
        }
    }

    /**
     * Generate Resources.
     */
    private function generateResources(array $resourceGroup): void
    {
        foreach ($resourceGroup as $namespace => $data) {
            $resources = [];
            array_walk_recursive($data, static function ($val) use (&$resources) {
                if (is_string($val) && ThorExtractor::isResourceClass($val)) {
                    $resources[] = sprintf('%s/resource/%s', ThorExtractor::basePath($val), ThorExtractor::baseClass($val));
                }
            });

            foreach ($data as $index => $val) {
                if (is_array($val) && !array_is_list($val)) {
                    $data[$index] = [...$val, '[key:string]' => 'any'];
                }
            }

            [$namespace, $routeGroup] = explode(':', $namespace);
            $name = sprintf('%s.ts', ucfirst($namespace));
            $path = sprintf('%s/%s/resource/%s', $this->path, $routeGroup, $name);

            if (!file_exists($p = dirname($path)) && !mkdir($p, 0777, true) && !is_dir($p)) {
                throw new \RuntimeException(sprintf('Directory "%s" was not created', $p));
            }

            file_put_contents($path, $this->renderTemplate('resource.ts.php', [
                'namespace' => $namespace,
                'data' => $data,
                'resources' => $resources,
            ]));
        }
    }
}
